version: '3.8'

services:
  jarvispy:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/jarvispy:latest
    pull_policy: always
    container_name: jarvispy-xxxx
    networks:
      - xxxx_network
    volumes:
      - './shared/disk:/jarvispy/disk:rw'
    ports:
      - "8001_xxxxtenant:8000"
    environment:
      - RUN_MODE=development
      - USERNAME=xxxx
      - ORGANIZATION=xxxx
      - TO_PERSIST_DATASOURCE_HOST=pgvector
      - VADALINGO_URL=http://vadalingo:8086
      - DATA_MANAGER_URL=http://data-manager:8085
      - VADALOG_URL=http://vadalog-parallel:8080
      - VADALOG_PARSER_URL=http://vadalog-parallel:8080
    restart: unless-stopped

  vadalog-parallel:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/prometheux-reasoner-premises-____:latest
    pull_policy: always
    container_name: vadalog-parallel-xxxx
    networks:
      - xxxx_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - './shared/disk:/vadalog-parallel/disk:rw'
      - './vadalog-parallel/pmtx.properties:/vadalog-parallel/pmtx.properties:rw'
      - './vadalog-parallel/spark-defaults.conf:/vadalog-parallel/spark-defaults.conf:rw'
      - './vadalog-parallel/localCheckpoints:/vadalog-parallel/localCheckpoints:rw'
      - './vadalog-parallel/tmp:/vadalog-parallel/tmp:rw'
      - './vadalog-parallel/log:/vadalog-parallel/log:rw'
    environment:
      - JAVA_OPTS=-Xmx4G
#      - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost
#    ports:
#      - "127.0.0.1:9090:9090"
    restart: unless-stopped

  data-manager:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/data-manager:latest
    pull_policy: always
    container_name: data-manager-xxxx
    networks:
      - xxxx_network
    volumes:
      - './shared/disk:/data-manager/disk:rw'
    restart: unless-stopped

  vadalingo:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/vadalingo:latest
    pull_policy: always
    container_name: vadalingo-xxxx
    networks:
      - xxxx_network
    volumes:
      - './shared/disk:/vadalingo/disk:rw'
    restart: unless-stopped

  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-xxxx
    networks:
      - xxxx_network
    restart: unless-stopped
    environment:
      POSTGRES_USER: prometheux
      POSTGRES_PASSWORD: postgres@prometheux
      POSTGRES_DB: prometheux
    volumes:
      - './postgres-data:/var/lib/postgresql/data:rw'

  jupyterlab:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/jupyter-lab:latest
    pull_policy: always
    container_name: jupyterlab-xxxx
    networks:
      - xxxx_network
    ports:
      - "8888:8888"
    volumes:
      - './shared/disk:/notebooks:rw'
    environment:
      - VADALOG_HOST=vadalog-parallel
      - VADALOG_PORT=8080
      - myToken=TbMcS530
      - myUrl=
    restart: unless-stopped

networks:
  xxxx_network:
    driver: bridge