version: '3.8'

services:
  vadalog-parallel:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/prometheux-reasoner-premises:latest
    container_name: vadalog-parallel
    # Host mode means it binds to the host's network stack.
    network_mode: "host"
    # 'ports:' is ignored in host network mode,
    # so you can remove or comment it out
    # ports:
    #   - "8080:8080"
    volumes:
      - './prometheux/shared/disk:/vadalog-parallel/disk:rw'
      - './prometheux/vadalog-parallel/pmtx.properties:/vadalog-parallel/pmtx.properties:rw'
      - './prometheux/vadalog-parallel/spark-defaults.conf:/vadalog-parallel/spark-defaults.conf:rw'
    environment:
      - JAVA_OPTS=-Xmx4G
    restart: unless-stopped

  data-manager:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/data-manager:latest
    container_name: data-manager
    # Host mode means it binds to the host's network stack.
    network_mode: "host"
    # 'ports:' is ignored in host network mode,
    # so you can remove or comment it out
    # ports:
    #   - "8085:8085"
    volumes:
      - './prometheux/shared/disk:/data-manager/disk:rw'
    restart: unless-stopped

  jupyterlab:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/jupyter-lab:new
    container_name: jupyterlab
    # Also use host networking
    network_mode: "host"
    # ports:
    #   - "8888:8888"
    volumes:
      - './prometheux/shared/disk:/notebooks:rw'
    environment:
      - VADALOG_HOST=localhost
      - VADALOG_PORT=8080
      - myToken= # leave empty for local installation
      - myUrl= # leave empty for local installation
    restart: unless-stopped
