version: '3.8'

services:
  vadalog-parallel:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/prometheux-reasoner-premises:latest
    pull_policy: always
    container_name: vadalog-parallel
    ports: ["8080:8080"]
    volumes:
      - ./prometheux/shared/disk:/vadalog-parallel/disk
      - ./prometheux/vadalog-parallel/pmtx.properties:/vadalog-parallel/pmtx.properties
      - ./prometheux/vadalog-parallel/spark-defaults.conf:/vadalog-parallel/spark-defaults.conf
    environment:
      JAVA_OPTS: -Xmx4G
    restart: unless-stopped
    networks: [backend]

  data-manager:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/data-manager:latest
    pull_policy: always
    container_name: data-manager
    ports: ["8085:8085"]
    volumes:
      - ./prometheux/shared/disk:/data-manager/disk
    restart: unless-stopped
    networks: [backend]

  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: prometheux
      POSTGRES_PASSWORD: postgres@prometheux
      POSTGRES_DB: prometheux
    restart: unless-stopped
    networks: [backend]

  jupyterlab:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/jupyter-lab:latest
    pull_policy: always
    container_name: jupyterlab
    ports: ["8888:8888"]
    volumes:
      - ./prometheux/shared/disk:/notebooks
    environment:
      VADALOG_HOST: vadalog-parallel
      VADALOG_PORT: 8080
    restart: unless-stopped
    networks: [backend]

  jarvispy:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/jarvispy:latest
    pull_policy: always
    container_name: jarvispy
    ports: ["8000:8000"]
    environment:
      RUN_MODE: development
    restart: unless-stopped
    networks: [backend]

  ui:
    image: 094284551733.dkr.ecr.eu-west-2.amazonaws.com/ui:latest
    pull_policy: always
    container_name: ui
    ports: ["3000:80"]
    environment:
      RUN_MODE: development
    restart: unless-stopped
    networks: [backend]

networks:
  backend: {}
